# Madlib written by Morgan and coded by Shona. 

celebrity = input("Enter a celebrity: ")
adjective1 = input("Enter an adjective: ")
noun = input("Enter a noun: ")
adjective2 = input("Enter an adjective: ")
feeling = input("Enter a feeling: ")
pronoun = input("Enter a pronoun: ")
name = input("Enter a name: ")
adjective3 = input("Enter an adjective: ")
chore = input("Enter a chore: ")
temperature = input("Enter a temperature: ")
food = input("Enter a food: ")
shoutout = input("Enter a exclamation: ")

print("Hi there! My name is", celebrity +".")
print("I'm a very", adjective1 +" cat.")
print("There's this", noun, "that is really", adjective2, "to me and I just feel", feeling,"about it.")
print(pronoun, "is called", name + ".")
print("It's really", adjective3, "being a cat.")
print("Sometimes I want to do something out there like", chore + ".")
print("Today I had a bowl of", temperature, food +".")
print(shoutout + "!")
